# Generated by Django 4.0.2 on 2022-02-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='precious', help_text='Student should enter their name here', max_length=30)),
                ('school', models.CharField(default='Akwa Ibom state university', help_text='the student school name', max_length=50)),
                ('dept', models.CharField(default='chemical engineering', help_text='enter your department here', max_length=40)),
                ('fact', models.TextField(help_text='history of the student', max_length=300)),
                ('inspiration', models.TextField(help_text='student inspiration', max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
