# Generated by Django 4.0.2 on 2022-02-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(default='static/img/gallery/about1.png', upload_to='ida'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='Precious', help_text='Student should enter their name here', max_length=30),
        ),
    ]
